package linear_regression;

public interface Model {
    /**
     * Given an x-value, return the corresponding y-value
     * generated by the model function.
     * @param x input value
     * @return y result value
     */
    double predict(double x);
}
